# Generated by Django 4.2.7 on 2026-02-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescanai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
    ]
