# Generated by Django 4.2.7 on 2026-02-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescanai', '0002_scan_risk_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebReconData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cms', models.JSONField(blank=True, default=list)),
                ('frameworks', models.JSONField(blank=True, default=list)),
                ('javascript_libraries', models.JSONField(blank=True, default=list)),
                ('web_servers', models.JSONField(blank=True, default=list)),
                ('programming_languages', models.JSONField(blank=True, default=list)),
                ('analytics', models.JSONField(blank=True, default=list)),
                ('security_headers', models.JSONField(blank=True, default=dict)),
                ('discovered_urls', models.JSONField(blank=True, default=list)),
                ('directories', models.JSONField(blank=True, default=list)),
                ('forms', models.JSONField(blank=True, default=list)),
                ('emails', models.JSONField(blank=True, default=list)),
                ('robots_txt_content', models.TextField(blank=True)),
                ('sitemap_urls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_recon', to='rescanai.scan')),
            ],
        ),
    ]
