# Generated by Django 4.2.7 on 2026-02-13 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescanai', '0003_webrecondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalServerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(default='localhost', max_length=200)),
                ('open_ports', models.JSONField(blank=True, default=list)),
                ('services_detected', models.JSONField(blank=True, default=list)),
                ('django_detected', models.BooleanField(default=False)),
                ('django_version', models.CharField(blank=True, max_length=50)),
                ('admin_panel_accessible', models.BooleanField(default=False)),
                ('admin_url', models.CharField(blank=True, max_length=200)),
                ('debug_mode_enabled', models.BooleanField(default=False)),
                ('static_files_accessible', models.BooleanField(default=False)),
                ('accessible_urls', models.JSONField(blank=True, default=list)),
                ('security_headers', models.JSONField(blank=True, default=dict)),
                ('missing_security_headers', models.JSONField(blank=True, default=list)),
                ('configuration_issues', models.JSONField(blank=True, default=list)),
                ('security_recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_server', to='rescanai.scan')),
            ],
        ),
    ]
