# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescanai', '0005_advancedvulnerabilitydata'),
    ]

    operations = [
        # Add CVSS and attack chain fields to Vulnerability model
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_vector',
            field=models.CharField(max_length=255, blank=True, help_text='CVSS v3.1 vector string'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_base_score',
            field=models.FloatField(null=True, blank=True, help_text='CVSS v3.1 base score (0-10)'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_exploitability_score',
            field=models.FloatField(null=True, blank=True, help_text='CVSS exploitability subscore'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_impact_score',
            field=models.FloatField(null=True, blank=True, help_text='CVSS impact subscore'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='attack_chain_id',
            field=models.CharField(max_length=50, blank=True, help_text='ID linking related vulnerabilities in attack chain'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='risk_prediction',
            field=models.JSONField(default=dict, blank=True, help_text='AI-based risk prediction metadata'),
        ),
        
        # Add attack chains and risk breakdown to Scan model
        migrations.AddField(
            model_name='scan',
            name='attack_chains',
            field=models.JSONField(default=list, blank=True, help_text='Detected attack chains'),
        ),
        migrations.AddField(
            model_name='scan',
            name='risk_breakdown',
            field=models.JSONField(default=dict, blank=True, help_text='Detailed risk analysis'),
        ),
        migrations.AddField(
            model_name='scan',
            name='risk_level',
            field=models.CharField(
                max_length=20,
                default='minimal',
                choices=[
                    ('minimal', 'Minimal'),
                    ('low', 'Low'),
                    ('medium', 'Medium'),
                    ('high', 'High'),
                    ('critical', 'Critical'),
                ],
                help_text='Categorical risk level'
            ),
        ),
    ]
