# Generated by Django 4.2.7 on 2026-02-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescanai', '0006_enhanced_risk_scoring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='attack_chains',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='risk_breakdown',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='attack_chain_id',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='cvss_base_score',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='cvss_exploitability_score',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='cvss_impact_score',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='cvss_vector',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='risk_prediction',
        ),
    ]
